env variables build validation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,45 @@ on:
   workflow_dispatch:
 
 jobs:
+  validateEnvs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate env
+        env:
+          GITHUB_USERNAME: ${{ secrets.GIT_HUB_CI_USER_NAME }}
+          GITHUB_TOKEN: ${{ secrets.GIT_HUB_CI_TOKEN }}
+          SRC_COM_ACCESS_TOKEN: ${{ secrets.SRC_COM_ACCESS_TOKEN }}
+          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
+          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
+          GITLAB_GROUP: ${{ secrets.GITLAB_GROUP }}
+          GITLAB_PROJECT: ${{ secrets.GITLAB_PROJECT }}
+        shell: bash
+        run: |
+          #!/bin/bash
+
+          set -e
+
+          MISSING=""
+          for env in GITHUB_USERNAME GITHUB_TOKEN SRC_COM_ACCESS_TOKEN ; do
+            if [ -z "${!env}" ]; then
+              MISSING="$MISSING,$env"
+            fi
+          done
+          FAIL=false
+          if [ -n "$MISSING" ]; then
+            FAIL=true
+          fi
+          for env in GITLAB_USERNAME GITLAB_TOKEN GITLAB_GROUP GITLAB_PROJECT ; do
+            if [ -z "${!env}" ]; then
+              MISSING="$MISSING, $env"
+            fi
+          done
+          if [ -n "$MISSING" ]; then
+            echo "Missing tokens: [${MISSING:2}]"
+          fi
+          if [ "$FAIL" == 'true' ]; then
+            exit 1
+          fi
 
   # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
   gradleValidation:
@@ -73,9 +112,14 @@ jobs:
           path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
           key: ${{ runner.os }}-plugin-verifier-${{ steps.properties.outputs.ideVersions }}
 
+      - name: Setup git user
+        run: |
+          git config --global user.email "3663856+jensim@users.noreply.github.com"
+          git config --global user.name "Jens Brimfors"
+
       # Run tests
       - name: Run Tests
-        run: ./gradlew test
+        run: ./gradlew test ${{ github.event.inputs.extra_args_gradle }}
         env:
           GITHUB_USERNAME: ${{ secrets.GIT_HUB_CI_USER_NAME }}
           GITHUB_TOKEN: ${{ secrets.GIT_HUB_CI_TOKEN }}
@@ -91,7 +135,7 @@ jobs:
 
       # Run IntelliJ Plugin Verifier action using GitHub Action
       - name: Run Plugin Verifier
-        run: ./gradlew runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}
+        run: ./gradlew runPluginVerifier ${{ github.event.inputs.extra_args_gradle }} -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}
 
   # Build plugin with buildPlugin Gradle task and provide the artifact for the next workflow jobs
   # Requires test job to be passed
